utk decoding
librempeg/librempeg pull request #14
Opened 2024-12-02 05:08 UTC by rouseabout

this adds utk and utk_r3 decoding based on <https://github.com/daddesio/utkencode> work.
utk_r3 uses the same underlying codec with escape code and buffer of raw pcm data

samples: https://github.com/daddesio/utkencode/tree/master/samples

utk is annoying becasue the very first packet contains a 15-bit header, while other packets do not. i have added a bsf to extract the header from the first packet and stuff it in extradata. also the codec uses little endian bitstream, neccessitating a seperate `extract_extradata_utk.c` file, because the existing file uses big endian get_bits.

2024-12-02 09:15 UTC, richardpl requested changes
Is there really good reason to use bitstream filter? Can you just seek back (while ensuring seeking back with avio? call)

2024-12-02 09:15 UTC, richardpl commented on libavcodec/Makefile
please fix wrong indentation

2024-12-02 09:15 UTC, richardpl commented on libavcodec/bsf/extract_extradata_utk.c
> +    init_get_bits8(&gb, data, size);
please check return value of init_get_bits8()

2024-12-02 09:15 UTC, richardpl commented on libavcodec/utkdec.c
> +        init_get_bits8(&gb, avctx->extradata, avctx->extradata_size);
please check return value of init_get_bits8(), if it fails next call may cause crash.

2024-12-02 09:15 UTC, richardpl commented on libavcodec/utkdec.c
> +static void utk_r3_decode_frame(UTKContext *ctx, GetBitContext * gb, const uint8_t * start)
please keep style similar to rest of codebase, no space between '*' and name of pointer variable.

2024-12-02 09:15 UTC, richardpl commented on libavcodec/utkdec.c
> +    init_get_bits8(&gb, avpkt->data, avpkt->size);
please check return value of this call.

2024-12-02 09:15 UTC, richardpl commented on libavcodec/utkdec.c
> +    frame->nb_samples = avpkt->duration;
If this value, frame duration in number of samples is always fixed use such value, if it depends on bitstream within packet use value from bitstream instead. Avoid using avpkt->duration for this.

2024-12-02 09:15 UTC, richardpl commented on libavformat/utkdec.c
> +    .p.long_name    = NULL_IF_CONFIG_SMALL("Maxis UTK (The Sims Online, SimCity 4)"),
Please do not put name of games in codec description - long_name. Instead feel free to mention games in commit log or somewhere after license header as comment.

2024-12-03 03:41 UTC, rouseabout commented on libavcodec/utkdec.c
> +    frame->nb_samples = avpkt->duration;
The number of samples per frame is variable, and is stored differently in the electronicarts sound data chunk and UTK file header. I am wondering how else to feed this value from the demuxer to the decoder?

Appreciate the review. I will make all other changes and update this branch.

2024-12-05 20:30 UTC, richardpl commented
merged with additional changes

2024-12-05 20:30 UTC, closed without merging